# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0cfad404313f3ddb31157aa742619155d546845f1ecbf6bee44456443cd041a384973e8d6f42c4be97cc5e4124fb717c8c4c4c9e5926536166f1255b3031ed5f

test:
  secret_key_base: e232d6228854a6437f701f34a73fa61c0d7676cc79e6c1069b816799c22c51d7a171e010441e6ca4df71bf67402d35b7a5f9ca3cc820392b407f8e383eee0039

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
